### ISSUE TITLE
Compatibility with Cave Dust

### ISSUE THREAD

**Issue by vico93** [Gibatron/dust#2]
Seems like having both Dusty and @LizIsTired's [Cave Dust](https://github.com/LizIsTired/cave_dust) cause the following mixin error to happen at startup:

```
RuntimeException: Non-unique Mixin config name dust.mixins.json used by the mods cavedust and dust
<html>at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:91)<br>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
```

Relevant issue on Cave Dust side: https://github.com/LizIsTired/cave_dust/issues/31

**Comment by makumaku1974** [comment]
waiting for the fix now.

**Comment by vico93** [comment]
@makumaku1974 see the issue i've created on cave_dust side
